image: barichello/godot-ci:3.1.1

stages:
  - export
  - deploy

before_script:
  - mkdir -v -p build/web

web:
  stage: export
  script:
    - godot -v --path Godot --export "HTML5" ../build/web/index.html
    - test -e ../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web
  only:
      - release
