name: Export and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export Godot Project
        uses: firebelley/godot-export@v6.0.0
        with:
          use_godot_3: false  # Use Godot 4.x
          cache: true
          relative_project_path: .  # Path to the Godot project
          presets_to_export: "Web"  # Make sure it matches the name in Godot's export settings
          relative_export_path: "exports/web"  # Where the exported files will be stored

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: exports/web  # Ensure this matches the export path
