name: Export and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Export Godot Project
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz"
          relative_project_path: .
          presets_to_export: "Web"
          relative_export_path: "exports/web"
          cache: true
          export_debug: false
          verbose: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: exports/web  # Ensure this matches the export path
