name: godot

on:
  push:
    paths:
      - "version"
      - ".github/workflows/blank.yml"
      - "export_presets.html.example"

env:
  WORKING_DIRECTORY: game

jobs:
  deploy:
    if: github.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

  

      - name: Create export directory
        run: mkdir html5

      - name: Create export_presets.cfg
        run: cp game/export_presets.html.example game/export_presets.cfg

      - name: Godot HTML5 export
        uses: dulvui/godot-html-export@v1
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }} 
          godot-version: 4.2
          create-export-preset-cfg: false

    
